todo_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # todo 관련된 일에 대한 요청은 todos app이 관리
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path, include
from . import views

app_name = 'todos'

urlpatterns = [
    # main 경로 요청이 들어오면, todos 앱 패키지 내에 있는
    # views.py 모듈 안에 있는 main 함수 실행
    path('main/', views.main, name = 'main'),
    # todo를 추가 할 수 있는 어떤 기능이 포함된 함수 만들고,
    # todo를 추가 할 수 있는 html 반환
    path('create/', views.create, name = 'create'),
]

todos/models.py
from django.db import models

# Create your models here.

todos/views.py
from django.shortcuts import render


todo_list = []
# Create your views here.
# 함수는 input에 대한 어떤 처리 후, output을 내는게 목적

# views.py에 만드는 모든 함수들의 목적?
# 사용자의 요청에 따라서 반환해야할 적절한 html을 내는게 목적
def main(request):
    work = request.GET.get('work')
    if work:
        todo_list.append(work)
    context = {
        'todo_list' : todo_list
    }

    return render(request, 'todos/main.html', context)


def create(request):
    return render(request, 'todos/create.html')



    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>할 일 목록 관리 프로젝트 메인 페이지</title>
</head>
<body>
  <a href="{% url "todos:main" %}">[MAIN]</a>
  <a href="{% url "todos:create" %}">[create]</a>

  {% comment %} 
   이걸 만드는 이유?
   모든 html에서 공통으로 사용할 영역을 이곳에서 작성한다.
   예를들어, bootstrap CDN이나, 혹은 페이지 전체를 아우르는 theme를 설정한
   CSS 파일, JS 파일 import nav bar와 가이 모든 페이지에서 다 보여줘야 할 영역.
   ex) articles/index.html에는 전체 게시글 목록을 보여줘야 함
   ex) articles/create.html에는 게시글 생성 페이지를 보여줘야 함
   이것을 위한 '영역' 지정
  {% endcomment %}
  {% block content %}
    {% comment %} 여기에 작성한 내용은 각자마다 서로 다른 고유 영역으로 표기 {% endcomment %}
  {% endblock content %}




  
</body>
</html>

todos/templates/todos/create.html
{% extends "base.html" %}
{% block content %}
  <h1>CREATE PAGE</h1>
  {% comment %} 
 app별로, urls.py를 따로 만들어서,
 url별로, 새로운 path 함수를 따로 적어서 관리

 app_name:url_name

  {% endcomment %}
  <form action="{% url "todos:main" %}" method = "GET">
    <input type="text" name = "work">
    <input type="submit" value="제출">
  </form>
{% endblock content %}

todos/templates/todos/main.html
{% extends "base.html" %}
{% block content %}
  <h1>MAIN PAGE</h1>
  <ul>
    {% for todo in todo_list %}
      <li>{{ todo }}</li> 
    {% empty %}
      <li>아직 할 일이 없습니다.</li>
    {% endfor %}

    
  </ul>
{% endblock content %}